# Changes here will be overwritten by Copier
_commit: fbe5ab3
_src_path: https://github.com/Ingenjorsarbete-For-Klimatet/ifk-python-template.git@hotfix/copier
author: IFK
email: info@ingenjorsarbeteforklimatet.se
module_name: test
package_name: test
project_description: Unspecified.
project_name: ifk-testing
